### ISSUE TITLE
Do you have the realization of the tensorflow？

### ISSUE THREAD

**Issue by lijun20** [wangshy31/Densely-Connected-CNN-with-Multiscale-Feature-Attention#1]
Caffe is not very well, do you have the realization of the tf or pytorch？

**Comment by qioqio** [comment]
i also  has this problem,o(╥﹏╥)o

**Comment by wangshy31** [comment]
> Caffe is not very well, do you have the realization of the tf or pytorch？

Sorry, I don't have such a plan currently.

**Comment by qioqio** [comment]
![image](https://user-images.githubusercontent.com/16997401/51427184-ca9f7800-1c2f-11e9-88bd-7b0aed810b83.png)

I have some confusion about the implementation of the model. As shown in the figure above, all of the dense layer outputs participate in the attention layer.
But it seems that only the last layer in the code has participated.

![image](https://user-images.githubusercontent.com/16997401/51427167-8318ec00-1c2f-11e9-9f73-2d277cc40e03.png)

**Comment by wangshy31** [comment]
> I have some confusion about the implementation of the model. As shown in the figure above, all of the dense layer outputs participate in the attention layer.
> But it seems that only the last layer in the code has participated.

see line 68-75 in `gen_model.py`:  the last layer has already included all the  proceeding  outputs by using concatenation
